version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./vuln_app:/var/www/html:rw,cached
    environment:
      # Optional: tune PHP for local dev if you want
      APP_ENV: local
    depends_on:
      - mysql
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    depends_on:
      - php
    ports:
      - "8101:8101"
    volumes:
      - ./vuln_app:/var/www/html:ro
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

volumes:
  db_data:
